# Config version
version: 0.3.2

# HTML Head settings
html:
  title: Links | Gaspar Pelayo  

# Main container settings
main:
  title: Gaspar (Rapax) Pelayo

# Blocks list
blocks:
  - title: LinkedIn
    icon: linkedin
    url: https://www.linkedin.com/in/gaspar-pelayo
    
  - title: Github
    icon: github
    url: https://github.com/gasparrrx6

  - title: Twitter
    icon: twitter
    url: https://twitter.com/gasparrrx6

  - title: Telegram
    icon: telegram
    url: https://t.me/gasparrrx6
