# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# HODL username
# username: "USUARIO" # < TU_USUARIO@hodl.ar

# NOSTR Settings
# nostr: # Sin el # adelante
#   npub: "TU_PUB" # Entre comillas dobles

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title: Links | Gaspar Pelayo # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#f9fafb"
  # cover_color: "#ff7070"

# Configuración Central
main:
  title: Gaspar (Rapax) Pelayo # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Sacale

  - title: LinkedIn
    icon: linkedin
    url: https://www.linkedin.com/in/gaspar-pelayo

  - title: Github
    icon: github
    url: https://github.com/rapax00

  - title: Twitter
    icon: twitter
    url: https://twitter.com/rapax00
  
  - title: Nostr
    icon: nostr
    url: https://iris.to/rapax@hodl.ar

  - title: Telegram
    icon: telegram
    url: https://t.me/rapax00

# Guardá el archivo haciendo click en Commit Changes, abajo
# Volvé a las instrucciones
